name: "Security Issue"
description: "Report a security vulnerability or potential security risk"
title: "[SECURITY] Brief description of the issue"
labels: ["security", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Security Vulnerability Disclosure**
        
        Please use this form to responsibly report a security issue in AAPP-MART.
        Do NOT publicly disclose sensitive details.  
        The maintainers will review your report privately.

  - type: textarea
    id: description
    attributes:
      label: "Vulnerability Description"
      description: "Explain the issue clearly. What is the vulnerability?"
      placeholder: "Example: Privilege escalation possible via X module..."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "Potential Impact"
      description: "What could an attacker achieve by exploiting this?"
      placeholder: "Example: Unauthorized access to system resources..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "Provide detailed steps to reproduce the issue."
      placeholder: |
        1. Go to...
        2. Run...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment Details"
      description: "Version, OS, configuration, or any relevant environment info."
      placeholder: "Example: Python 3.11, Ubuntu 22.04, AAPP-MART v0.1.0"
    validations:
      required: false

  - type: textarea
    id: mitigation
    attributes:
      label: "Possible Mitigation (Optional)"
      description: "If you have an idea for a fix, describe it here."
      placeholder: "Example: Validate input before processing..."
    validations:
      required: false

  - type: checkboxes
    id: confidentiality
    attributes:
      label: "Confidentiality Confirmation"
      description: "Please confirm the following"
      options:
        - label: "I confirm that I have NOT publicly disclosed this vulnerability."
          required: true
